### ISSUE TITLE
Aseprite Translation Manager

### ISSUE THREAD

**Issue by ghost** [aseprite/languages#14]
Hi to all translators of Aseprite!

I wrote a program "Aseprite Translation Manager" that can scan your translation INI file (any language) by comparing it to Aseprite’s en.ini file (in folder \data\strings).

Download the program and manual here to scan your own translation INI file in a very easy way and keep it up to date with latest Aseprite version.

https://github.com/pixelartgirl/Aseprite-Translation-Manager

PixelArtGirl

**Comment by ghost** [comment]
The maintainers of the Italian and French translation of Aseprite are already using it.
My Dutch translation will be available soon, also checked by my tool.

**Comment by Flaconia** [comment]
Thank you so much @pixelartgirl I'm using your tool right now to update my it translation (it's been sitting there for a while now).
It's way better than just manually search for differences, and it doesn't require translators to be familiar with Diff tools used by coders.

**Comment by ghost** [comment]
I'm a beginner programmer too and this is EXACTLY what this tool is for: fast and easy comparing Aseprite translation files (no knowledge required).  
Please report any bugs you find, because I want it to be completely bug free and 100% correctly comparing INI files.

**Comment by dacap** [comment]
Closing this as we're going to use Weblate for translations: https://hosted.weblate.org/engage/aseprite/
