### ISSUE TITLE
Some sentence problems in 'en.ini'  

### ISSUE THREAD

**Issue by TakWolf** [aseprite/languages#29]
```
[brush_slot_params]
save_brush = Save Brush Here
```

![b4882d7e8ea0a28c9c35091527b13ce6](https://github.com/aseprite/languages/assets/6064962/5538abce-fff4-4a75-9fb4-f8a9cec12bc5)

Should we need `Here`?

```
[brush_slot_params]
save_brush = Save Brush
```

@66six11

**Comment by TakWolf** [comment]
```
[timeline_conf]
first_frame = First Frame:

[options]
default_first_frame = Default First Frame:
```

Uncertain whether the two have the same function, do we need a unified text?

![f3108226efec61372476ef5c739b2fc6](https://github.com/aseprite/languages/assets/6064962/9c37ceef-2a07-47fc-860d-79f46c4790f3)

![f2d0b0b1448fc8f9559c740edacfa270](https://github.com/aseprite/languages/assets/6064962/08dbc609-4665-4420-a007-7b6ae98a231b)

**Comment by TakWolf** [comment]
Duplicate shortcut key configuration items:

There's no problem with the strings, it seems like a ui component bug.



<img width="1170" alt="image" src="https://github.com/aseprite/languages/assets/6064962/381e78f2-134f-4568-bc51-1fe128220972">

<img width="1165" alt="image" src="https://github.com/aseprite/languages/assets/6064962/c08c1596-01cb-4360-8322-715fd2a0af44">
<img width="1186" alt="image" src="https://github.com/aseprite/languages/assets/6064962/a944d1f2-a490-408f-9455-1fc82815a309">
<img width="1010" alt="image" src="https://github.com/aseprite/languages/assets/6064962/ea42f6ae-dc06-4bce-9539-16b1a3aaff77">

Not only the above, there are also many more

**Comment by dacap** [comment]
> Should we need `Here`?

We could remove the "Here" word, anyway as there are plans to re-design this popup dialog (#175), probably will have a simpler text or just a save icon (or a "Save" tooltip).

> Uncertain whether the two have the same function, do we need a unified text?

The "Default First Frame" is for new documents, and the "First Frame" is for the active sprite. Probably we could just use the "First Frame" re-designing the Timeline preferences (related to #1485) with something like Background or Grid sections:

```
timeline_for_new_docs = Timeline for New Documents
timeline_for_active_doc = Timeline for the Active Document
first_frame = First Frame:
```
etc.

> Duplicate shortcut key configuration items:

I'll try to take a look to this next week.

**Comment by TakWolf** [comment]
```
[layer_properties]
luminosity = Luminosity
```

Is here should be `luminance`?

-------------------------

Update:

Photoshop seems to be using `Luminosity`

Should we change all `luminance` to `luminosity`

```
sort_by_luminance = Sort by Luminance
```

![{D3F19E64-968E-EA33-1968-643793B0E68A}](https://github.com/aseprite/languages/assets/6064962/1e8ff007-b618-4b8f-8ef9-4a2126135566)


----------------------

Update 2:

```
color_hsl_lightness = Color: HSL Lightness
```

And I also found a `Lightness`. Is this should be `brightness` or `luminosity`?

![903d62b5e6431bffacf6337a5f66bd01](https://github.com/aseprite/languages/assets/6064962/13028160-1bb8-4aa4-a82d-7b6fcf7e24f0)

**Comment by TakWolf** [comment]
Not sure, confirmation needed!

```
[commands]
ToggleOtherLayersOpacity = Toggle Other Layers Opacity
ToggleOtherLayersOpacity_PreviewEditor = Toggle Other Layers Opacity in Preview
```

Does this mean:

```
Toggle Other Layers Visibility
Toggle Other Layers Visibility in Preview
```

--------------------------

```
[commands]
SwitchNonactiveLayersOpacity = Switch Nonactive Layers Opacity
```

What do `Nonactive` layers refer to?

**Comment by TakWolf** [comment]
```
rewind_on_stop = Rewind on Stop
rewind_on_stop_tooltip = The 'Stop' button should rewind the animation\nwhere it was started.
```

Does `where it was started`  mean `the selected frame`?

**Comment by TakWolf** [comment]
```
[context_bar]
all_layers = All Layers
current_layer = Current Layer
first_ref_layer = First Reference Layer
```

Is the description accurate? It may be as follows:  (The text is only for illustration purposes)

```
all_layers = All visible Layers
current_layer = Current Layer （Whether visible or not）
first_ref_layer = All visible Reference Layer
```

**Comment by dacap** [comment]
> Is here should be `luminance`?

As you saw, it's `Luminosity`, it's a standard color blend mode:

https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode#effect_of_different_mix-blend-mode_values

> Should we change all `luminance` to `luminosity`

Technically it should be called "luma", which is "relative luminance" with (approximated) gamma-compressed components:

https://en.wikipedia.org/wiki/Luma_(video)#Use_of_relative_luminance

I would prefer to keep `Luminance` in this case.

> And I also found a `Lightness`. Is this should be `brightness` or `luminosity`?

It's Lightness from HSL. It cannot be brightness because it looks like HSV is called Hue/Saturation/Brightness https://en.wikipedia.org/wiki/HSL_and_HSV

Please create one issue for each of these questions, I cannot follow all comments right now and I prefer to answer one per time.

**Comment by TakWolf** [comment]
@dacap 
Sorry, I will split the remaining valid issues later
