### ISSUE TITLE
Add Hungarian

### ISSUE THREAD

**Issue by smileyhead** [aseprite/languages#34]
Can you please add Hungarian to the Weblate project? I would like to translate Aseprite to Hungarian.

Thanks in advance.

**Comment by dacap** [comment]
Added in the weblate project, we'll see if there is some more interest to translate to Hungarian: https://hosted.weblate.org/projects/aseprite/aseprite/hu/

**Comment by smileyhead** [comment]
I've just finished the translation, so it's ready for testing.
