### ISSUE TITLE
Create a transifex translation project

### ISSUE THREAD

**Issue by EmmanuelMess** [aseprite/languages#8]
Create a transifex translation project to more easily add translations to the project.

**Comment by dacap** [comment]
We would like to provide an easier way to translators to participate and update their translations, transifex is too expensive at the moment. Is there other alternatives? Or maybe we can create something in the website itself or something in this github project for this purpose.

I will try to create a script to create patches (differences) between releases in the `en.ini` file and store those patches in this same repository at the moment.

**Comment by EmmanuelMess** [comment]
> We would like to provide an easier way to translators to participate and update their translations, transifex is too expensive at the moment. 

~~AFAIK~~ Transifex is free for opensource projects.

Edit: 
> What are the basic requirements to qualify as an Open Source account?
> We are proud and humbled to be hosting the largest Open Source translation community in the world. We offer Transifex for free to Open Source projects that have no funding, revenue, and/or commercialization model. If you have a question whether your organization qualifies for our Open Source program, please contact us.

[Source](https://www.transifex.com/pricing/).

Edit 2:
I just realized the "that have no funding, revenue, and/or commercialization model" part, ups.

Maybe if you separate the project so that the opensource part is only the translations and it generates no revenue it will qualify?

**Comment by EmmanuelMess** [comment]
Maybe [Crowdin Annual Micro](https://crowdin.com/pricing#annual)?

**Comment by ghost** [comment]
Hi

Please see this issue: https://github.com/aseprite/languages/issues/14

I believe my tool Aseprite Translation Manager is very handy to update translation files because it tells what strings are missing or should be removed by comparing to en.ini
It's Windows only because it uses Windows Forms.

PixelArtGirl

**Comment by dacap** [comment]
We're going to use Weblate to unify all translations: https://hosted.weblate.org/engage/aseprite/
